version: "3"

services:
  db:
    container_name: db
    image: postgres:14.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./.env.docker
    networks:
      - servernet

  server:
    container_name: ManageOffice
    build: .
    restart: always
    expose:
      - 8000
    volumes:
      - media_data:/app/media
      - static_data:/app/static
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - servernet

volumes:
  media_data:
  static_data:
  postgres_data:

networks:
  servernet:
    driver: bridge